### ISSUE TITLE
Getting error when running code

### ISSUE THREAD

**Issue by antriksh63** [harusametime/RUSBoost#2]
Traceback (most recent call last):
  File "RUSBoost.py", line 177, in <module>
    rus.learning()
  File "RUSBoost.py", line 63, in learning
    if self.Y[i] == self.clf[k].predict(self.X[i]):
  File "/home/antriksh/.local/lib/python2.7/site-packages/sklearn/tree/tree.py", line 412, in predict
    X = self._validate_X_predict(X, check_input)
  File "/home/antriksh/.local/lib/python2.7/site-packages/sklearn/tree/tree.py", line 373, in _validate_X_predict
    X = check_array(X, dtype=DTYPE, accept_sparse="csr")
  File "/home/antriksh/.local/lib/python2.7/site-packages/sklearn/utils/validation.py", line 441, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[0.49 0.29 0.48 0.5  0.56 0.24 0.35].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

How do I resolve this?

**Comment by harusametime** [comment]
@antriksh63 
Thank you for reporting this issue.
This code is not maintained for a long time, and may get incompatible with the latest scikit-learn.
Using `self.X[i].reshape(-1,1)` instead of `self.X[i]` may fix this bug as the error message says.

Now I am on the business trip, and have no environment for Python 2. If you are okay, I want to rewrite this code with Python 3 and fix the bug.
